# Generated by Django 5.1.4 on 2025-01-03 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('learning', 'Learning'), ('known', 'Already known'), ('repeating', 'Repeating'), ('learned', 'Fully learned')], default='selected', max_length=15)),
                ('english_words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.englishwords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
